name: PromotionEssentials
authors: [TekkitCommando]
version: 1.0.0

depend: [Vault]

main: me.tekkitcommando.promotionessentials.PromotionEssentials

commands:
  apply:
    usage: /apply <password>
  token:
    usage: /token <token>